//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X10D {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("X10D.src.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count must be greater than or equal to 0..
        /// </summary>
        internal static string CountMustBeGreaterThanOrEqualTo0 {
            get {
                return ResourceManager.GetString("CountMustBeGreaterThanOrEqualTo0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashAlgorithm&apos;s Create method returned null referenece..
        /// </summary>
        internal static string HashAlgorithmCreateReturnedNull {
            get {
                return ResourceManager.GetString("HashAlgorithmCreateReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashAlgorithm does not offer Create method..
        /// </summary>
        internal static string HashAlgorithmNoCreateMethod {
            get {
                return ResourceManager.GetString("HashAlgorithmNoCreateMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length must be greater than or equal to 0..
        /// </summary>
        internal static string LengthGreaterThanOrEqualTo0 {
            get {
                return ResourceManager.GetString("LengthGreaterThanOrEqualTo0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be greater than {1}.
        /// </summary>
        internal static string LowerCannotBeGreaterThanUpper {
            get {
                return ResourceManager.GetString("LowerCannotBeGreaterThanUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxValue must be greater than or equal to 0.
        /// </summary>
        internal static string MaxValueGreaterThanEqualTo0 {
            get {
                return ResourceManager.GetString("MaxValueGreaterThanEqualTo0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxValue must be greater than or equal to minValue.
        /// </summary>
        internal static string MaxValueGreaterThanEqualToMinValue {
            get {
                return ResourceManager.GetString("MaxValueGreaterThanEqualToMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream does not support reading..
        /// </summary>
        internal static string StreamDoesNotSupportReading {
            get {
                return ResourceManager.GetString("StreamDoesNotSupportReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream does not support writing..
        /// </summary>
        internal static string StreamDoesNotSupportWriting {
            get {
                return ResourceManager.GetString("StreamDoesNotSupportWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0}} does not inherit {typeof(Attribute)}.
        /// </summary>
        internal static string TypeDoesNotInheritAttribute {
            get {
                return ResourceManager.GetString("TypeDoesNotInheritAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0}} is not a class..
        /// </summary>
        internal static string TypeIsNotClass {
            get {
                return ResourceManager.GetString("TypeIsNotClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0}} is not an interface..
        /// </summary>
        internal static string TypeIsNotInterface {
            get {
                return ResourceManager.GetString("TypeIsNotInterface", resourceCulture);
            }
        }
    }
}
