name: DocFX

on:
  push:
    branches: [ main ]

jobs:
  docfx:
    runs-on: ubuntu-latest
    name: Publish Documentation
    steps:
    - uses: actions/checkout@v1
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: docfx_project/docfx.json
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: docfx_project/_site
        GH_PAT: ${{ secrets.GH_PAT }}
